### ISSUE TITLE
GLPK assumes that variables are positive

### ISSUE THREAD

**Issue by Drup** [ktahar/ocaml-lp#1]
As said in the title, if no bounds are given, GLPK assumes that it's `[0,+inf[`. I'm not sure how the other solver behaves.
It might be worth putting explicit `]-inf,+inf[` bounds by default to ensure consistent behaviour across solvers.

**Comment by ktahar** [comment]
Most of the solvers assumes `[0, +inf)` bounds if it's not given, as well as GLPK.
e.g. [CPLEX](https://www.ibm.com/docs/en/icos/12.7.1.0?topic=representation-bounds-in-lp-file-format) and [Gurobi](https://www.gurobi.com/documentation/9.1/refman/variables.html).
Non-negative variable looks like the default in mathematical programming context.

Thus, `Lp.var` defaults the bounds to `[0, +inf)`. 
I added comments on this at 2ee56e7994f46a97536e11c27456663d930e1579.
Thank you for pointing out.

**Comment by Drup** [comment]
Fair enough, the documentation makes this clear :+1:
